### ISSUE TITLE
in `get_image_data': undefined local variable or method `compression'

### ISSUE THREAD

**Issue by u338steven** [chef-boneyard/win32-clipboard#5]
Error:

``` Error
C:/ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.1/lib/win32/clipboard.rb:374:in `get_image_data': undefined local variable or method `compression' for Win32::Clipboard:Class (NameError)
        from C:/ruby/lib/ruby/gems/2.0.0/gems/win32-clipboard-0.6.1/lib/win32/clipboard.rb:117:in `data'
        from test.rb:4:in `block in <main>'
        from test.rb:3:in `open'
        from test.rb:3:in `<main>'
```

Source:

``` ruby:test.rb
require 'win32/clipboard'

File.open('foo.bmp', 'wb'){ |fh|
  fh.write Win32::Clipboard.data(Win32::Clipboard::DIB)
}
```

I'm using the following:

Windows 7 (x64)
Ruby 2.0.0p353 (2013-11-22)[x64-mingw32]
win32/clipboard 0.6.1

**Comment by u338steven** [comment]
Sorry...I made a mistake.
Please check Issue #6.
